### ISSUE TITLE
Compass Calibration WorkFlow

### ISSUE THREAD

**Issue by MikeWoots** [dji-sdk/Mobile-UILibrary-Android#27] opened 2017-11-08 08:28 UTC
Hi

I would really appreciate some feedback on the CompassCalibrationWorkflow class in the Android UI library. My understanding of documentation [DJI UI reference](https://developer.dji.com/api-reference/android-uilib-api/Widgets/CompassCalibratingWorkFlow.html#compasscalibratingworkflow_startcalibration_inline) is that calling startCalibration will bring up a dialog which guides the user through the calibration process. However, when I call this method nothing is displayed. Below is how I am currently implementing this.

    CompassCalibratingWorkFlow.startCalibration(new ActionCallback() {
            @Override
            public void onSuccess() {
            }
            @Override
            public void onFailure(@NonNull DJIError djiError) {
            }
        });

I am I using this incorrectly or is this a bug in the library?

My setup: 
DJI Android SDK version: 4.3.2
DJI UI Library version: 4.3.2
Android system versions: 7.0, 5.0
DJI product: Phantom 4, Mavic Pro

**Comment by talobin** [comment] 2017-11-30 08:46
@MikeWoots 
We cannot reproduce this bug.
Can you make sure the aircraft is connected?
If the aircraft is not connected. Nothing will show up and that is expected

**Comment by MikeWoots** [comment] 2017-11-30 13:03
@talobin Thanks for getting back to me. Can you confirm that the code snippet in my previous post is the correct way of implementing the calibration workflow? Also is it possible you can post some images or examples of how the calibration UI looks when running correctly?

I have checked with the drone connected but I will try again and let you if it works.

**Comment by talobin** [comment] 2018-01-02 17:55
@MikeWoots 
The usage is correct.
Again, please make sure the drone is connected and SDK has been registered.
Thanks.
I will go ahead and close this issue.
If you still see the same problem, feel free to reopen.

**Closed by talobin** 2018-01-02 17:55 UTC

**Comment by radjkarl** [comment] 2021-02-16 06:12
You need 
`    <dji.ux.workflow.CompassCalibratingWorkFlow
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>`
in your layout xml to show the compass calibration routine.

**Comment by ernesto13edop** [comment] 2022-11-23 11:38
Currently this widget is still not working on the M300 drone.
